# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DALISwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DALISwift
  pod 'Google/SignIn'
  pod 'ProximityKit', '~> 1.2'
  pod 'SCLAlertView'
  pod 'DALI'

  target 'DALISwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DALISwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'DALI Lab tvOS' do
  use_frameworks!

  pod 'DALI'
end
